# Generated by Django 5.1.15

from django.db import migrations, models


def _migrate_legacy_sla_notified(apps, schema_editor):
    """Convert the legacy one-shot ``sla_notified`` boolean in
    ``InboxMessage.extra`` to the new ``sla_state`` dict format.

    The new ``check_sla()`` already handles legacy rows gracefully at runtime,
    but this data migration cleans them up eagerly so the column is consistent
    after deploy.
    """
    InboxMessage = apps.get_model("inbox", "InboxMessage")

    for msg in InboxMessage.objects.filter(extra__has_key="sla_notified").only("id", "extra"):
        msg.extra.pop("sla_notified", None)
        msg.extra["sla_state"] = {
            "fp": "legacy",
            "notified_at": "",
        }
        msg.save(update_fields=["extra"])


def _reverse_migrate(apps, schema_editor):
    """Reverse: convert ``sla_state`` back to ``sla_notified``."""
    InboxMessage = apps.get_model("inbox", "InboxMessage")

    for msg in InboxMessage.objects.filter(extra__has_key="sla_state").only("id", "extra"):
        msg.extra.pop("sla_state", None)
        msg.extra["sla_notified"] = True
        msg.save(update_fields=["extra"])


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxslaconfig",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text=(
                    "Incremented whenever target_response_minutes or is_active "
                    "changes, so that check_sla() can detect config updates and "
                    "re-evaluate overdue notifications."
                ),
            ),
        ),
        migrations.RunPython(
            _migrate_legacy_sla_notified,
            _reverse_migrate,
        ),
    ]
