# Generated by Django 5.1.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0016_alter_contentcategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="recurrence_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Source post from which this recurrence was cloned. NULL for non-recurring posts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurrence_clones",
                to="composer.post",
            ),
        ),
        # Index covering the dedup query: (recurrence_source, scheduled_at__date)
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["recurrence_source", "scheduled_at"],
                name="idx_post_recur_source_sched",
            ),
        ),
    ]
